# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
    push:
        branches: ["*"]
    pull_request:
        branches: ["*"]

jobs:
    build:
        runs-on: ubuntu-latest
        name: "Latest (Node ${{ matrix.node-version }})"

        strategy:
            matrix:
                node-version: [20.x, 22.x, 24.x]

        steps:
            - uses: actions/checkout@v5
            - name: Install pnpm
              uses: pnpm/action-setup@v5
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v5
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
            - run: pnpm install --frozen-lockfile
            - run: pnpm run lint
            - run: pnpm run build-all
            - run: pnpm run test-ci

    compat:
        runs-on: ubuntu-latest
        name: "Angular ${{ matrix.angular-version }}"

        strategy:
            matrix:
                include:
                    - angular-version: 18
                      node-version: 18.x
                      config-dir: compat/a18
                    - angular-version: 19
                      node-version: 18.x
                      config-dir: compat/a19
                    - angular-version: 20
                      node-version: 20.x
                      config-dir: compat/a20
                    - angular-version: 21
                      node-version: 22.x
                      config-dir: compat/latest

        steps:
            - uses: actions/checkout@v5
            - name: Install pnpm
              uses: pnpm/action-setup@v5
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v5
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Use compat config
              run: |
                  cp ${{ matrix.config-dir }}/package.json package.json
                  cp ${{ matrix.config-dir }}/angular.json angular.json
            - run: pnpm install --no-frozen-lockfile
            - run: pnpm run build-all
            - run: pnpm run test-ci
